version: '3'

services:
  api:
    build: api
    container_name: api
    restart: unless-stopped
    env_file:
      api.env
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend

  mongodb:
    image: mongo:4.2.2
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    env_file:
      mongodb.env
    volumes:
      - /data/db:/data/db
    networks:
      - backend

  front:
    build: front
    container_name: front
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
